### PR TITLE
TimeoutHTTPSConnection fixes

### PR DESCRIPTION
**Pull request by philiptzou**
~~This is basically a replication of #9, which issued 3 years ago but never get merged. I rebased the old revisions onto latest `superlance` and did some PEP8 fix, that's all.~~

~~The reason I want to help it being merged is that I ran into the same problem (`'NoneType' object has no attribute 'settimeout'`). At the beginning I thought to fix it by my own but soon I found someone already did it in #9.~~

This time just try to fix the `'NoneType' object has no attribute 'settimeout'` problem when using `TimeoutHTTPSConnection`.

### CODE REVIEW

**Comment by mnaberez** [comment]
> The reason I want to help it being merged is that I ran into the same problem ('NoneType' object has no attribute 'settimeout')

This PR is mixing a lot of unrelated changes (an SSL fix, new features, and PEP8 style changes). If you want to submit a focused PR that just fixes `settimeout`, I'll merge it.  It looks like there was unfinished discussion in 2014 on the new features introduced in #9.

**Comment by philiptzou** [comment]
@mnaberez ok, I'll try to separate the settimeout fix out.

**Comment by philiptzou** [comment]
@mnaberez the `settimeout` fix has been separated.

**Comment by mnaberez** [comment]
Thanks!
